### ISSUE TITLE
Unable to claim interface -7

### ISSUE THREAD

**Issue by G33kLabs** [nguyer/node-kinect#11]
Hello Pedro,

I'm just buying a Kinect 360 this morning for a robotic's project and I've got an usb connection error when using node-kinect :

```
MacBook-Pro:kinect g33k$ node index.js
Unable to claim interface -7
Could not claim interface on audio: -99
Failed to open motor subddevice or it is not disabled.Failed to open audio subdevice or it is not disabled.
/Users/g33k/Sites/kinect/node_modules/kinect/kinect.js:67
  var kContext = new kinect.Context(options.device);
                 ^
Error: Could not open device number

    at new module.exports (/Users/g33k/Sites/kinect/node_modules/kinect/kinect.js:67:18)
    at Object.<anonymous> (/Users/g33k/Sites/kinect/index.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

I've tried on my both macbook pro and it's always the same error.

Have you an idea about what I've missed ?

On the other hand, all binaries 'freenect-*' like freenect-glview works.

```
MacBook-Pro:~ g33k$ freenect-glview
Kinect camera test
Number of devices found: 1
Trying to open ./audios.bin as firmware...
Trying to open /Users/g33k/.libfreenect/audios.bin as firmware...
Trying to open /usr/local/share/libfreenect/audios.bin as firmware...
Trying to open /usr/share/libfreenect/audios.bin as firmware...
Trying to open ./../Resources/audios.bin as firmware...
upload_firmware: failed to find firmware file.
upload_firmware failed: -2
GL thread
write_register: 0x0105 <= 0x00
write_register: 0x0006 <= 0x00
write_register: 0x0012 <= 0x03
write_register: 0x0013 <= 0x01
write_register: 0x0014 <= 0x1e
write_register: 0x0006 <= 0x02
write_register: 0x0017 <= 0x00
write_register: 0x000c <= 0x00
write_register: 0x000d <= 0x01
write_register: 0x000e <= 0x1e
write_register: 0x0005 <= 0x01
```

Thanks for your work and your help !

Have a good day!

**Comment by nguyer** [comment]
Hi, @G33kLabs. I am the new maintainer of this repo now, and I'm looking through the open issues. Is this still an issue for you with the latest version?

**Comment by G33kLabs** [comment]
Hi nguyer ! 

I'll try this week-end, the kinect is inside the robot and in the garage of my friend.

Thanks for maintaining again this repo !

**Comment by nguyer** [comment]
Closing this for now, but if the issue comes up again, feel free to re-open.
