### ISSUE TITLE
npm install fails when using NodeJS v0.12.x

### ISSUE THREAD

**Issue by emilsoman** [nguyer/node-kinect#14]
I get the following error when I try `npm install` when I'm on node v0.12.0 (Works fine when I tried on node v0.10.25) : 

```
> kinect@0.3.0 install /Users/emil/Testing/node-kinect
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/kinect/src/kinect.o
../src/kinect.cc:27:19: error: expected class name
  class Context : ObjectWrap {
                  ^
../src/kinect.cc:41:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
      static Handle<Value>  New              (const Arguments& args);
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:42:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
      static Context*       GetContext       (const Arguments &args);
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:45:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
      static Handle<Value>  Close            (const Arguments &args);
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:48:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
      static Handle<Value>  Led              (const Arguments &args);
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:51:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
      static Handle<Value>  Tilt             (const Arguments &args);
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:54:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
      static Handle<Value>  SetDepthCallback (const Arguments &args);
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:57:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
      static Handle<Value>  SetVideoCallback (const Arguments &args);
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:60:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
      static Handle<Value>  Pause            (const Arguments &args);
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:63:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
      static Handle<Value>  Resume           (const Arguments &args);
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:69:7: error: unknown type name 'Buffer'
      Buffer*               videoBuffer_;
      ^
../src/kinect.cc:71:7: error: unknown type name 'Buffer'
      Buffer*               depthBuffer_;
      ^
../src/kinect.cc:83:29: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  Context::GetContext(const Arguments &args) {
                            ^~~~~~~~~
                            v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:84:12: error: use of undeclared identifier 'ObjectWrap'
    return ObjectWrap::Unwrap<Context>(args.This());
           ^
../src/kinect.cc:84:31: error: 'Context' does not refer to a value
    return ObjectWrap::Unwrap<Context>(args.This());
                              ^
../src/kinect.cc:27:9: note: declared here
  class Context : ObjectWrap {
        ^
../src/kinect.cc:84:44: error: member access into incomplete type 'const v8::internal::Arguments'
    return ObjectWrap::Unwrap<Context>(args.This());
                                           ^
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/kinect.cc:113:25: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  Context::Resume(const Arguments& args) {
                        ^~~~~~~~~
                        v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kinect.cc:115:12: error: no matching function for call to 'Undefined'
    return Undefined();
           ^~~~~~~~~
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/kinect.cc:127:24: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  Context::Pause(const Arguments& args) {
                       ^~~~~~~~~
                       v8::internal::Arguments
/Users/emil/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/kinect/src/kinect.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/emil/.nvm/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/emil/.nvm/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/emil/Testing/node-kinect
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/emil/.nvm/v0.12.0/bin/node" "/Users/emil/.nvm/v0.12.0/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! kinect@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kinect@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the kinect package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls kinect
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/emil/Testing/node-kinect/npm-debug.log
```

**Comment by nguyer** [comment]
Ah okay. I haven't tried with Node 12 yet. I will try it when I get a chance. Thanks for opening the issue!

**Comment by theoperatore** [comment]
Hello! Any update on the progress of this issue? Otherwise, I'll probably try to look into upgrading the lib to use Node v0.12.4+ if that's ok.

**Comment by nguyer** [comment]
@theoperatore I have been pretty busy lately and haven't had a chance to try it yet. If you get it working, please feel free to create a PR.

**Comment by TrevorJTClarke** [comment]
I am getting the same issue, @theoperatore have you figured it out yet?

**Comment by pbucci** [comment]
Same issue on Mac OSX—other people having similar issues with node-gyp, tried upgrading to newest Xcode + CLT. Fixed by downgrading node to v0.10.36.

**Comment by onlyfly34** [comment]
I'm using Mac OSX El Capitan. Also fixed by downgrading node to v0.10.36 when running npm install.
But when I run npm test,I got some errors:

> kinect@0.3.0 test /Users/onlyfly34/Desktop/node-kinect
> mocha test/*.js
> Base
>    1) Initializes and shuts down
> Failed to open camera subdevice or it is not disabled.Failed to open motor subddevice or it is not disabled.Fai  
>    2) Fails on device not present activation
>    3) Fails to activate unknown feature
> 
>  Depth
>    4) "before each" hook for "should allow to pass in a depth callback"
> 
>  Led
>    5) "before each" hook for "should throw when no string is specified"
> 
>  Tilt
>    6) "before each" hook for "should throw when no angle is specified"
> 
>  Video
>    7) "before each" hook for "should allow to pass in a depth callback"
> 
>  0 passing (16s)
>  7 failing
> 
>  1) Base Initializes and shuts down:
>     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
> 
>  2) Base Fails on device not present:
>     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
> 
>  3) Base activation Fails to activate unknown feature:
>     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
> 
>  4) Depth "before each" hook for "should allow to pass in a depth callback":
>     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
> 
>  5) Led "before each" hook for "should throw when no string is specified":
>     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
> 
>  6) Tilt "before each" hook for "should throw when no angle is specified":
>     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
> 
>  7) Video "before each" hook for "should allow to pass in a depth callback":
>     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
> 
> npm ERR! Test failed.  See above for more details.
> npm ERR! not ok code 0

**Comment by pbucci** [comment]
Yeah, I got similar errors, but was still able to run w/o major issues. I suggest testing w/o the provided test package.

**Comment by pbucci** [comment]
Also on El Capitan **
