### ISSUE TITLE
Install problem: libfreenect/libfreenect.h: No such file or directory. Node: v8.2.1 Linux: 3.16.0-38-generic.

### ISSUE THREAD

**Issue by corpr8** [nguyer/node-kinect#19]
Install blows up looking for libfreenect (Node: v8.2.1 Linux: 3.16.0-38-generic):

apt install libfreenect-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libfreenect-dev is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 20 not to upgrade.

npm install

<pre>
> kinect@0.3.0 install /home/paul/node-kinect
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.2.1
gyp verb command install [ '8.2.1' ]
gyp verb install input version string "8.2.1"
gyp verb install installing version: 8.2.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.2.1
gyp verb ensuring nodedir is created /home/paul/.node-gyp/8.2.1
gyp verb created nodedir /home/paul/.node-gyp/8.2.1
gyp http GET https://nodejs.org/download/release/v8.2.1/node-v8.2.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.2.1/node-v8.2.1-headers.tar.gz
gyp sill ignoring from tarball include
gyp sill ignoring from tarball include/node
gyp verb extracted file from tarball include/node/android-ifaddrs.h
gyp verb extracted file from tarball include/node/common.gypi
gyp verb extracted file from tarball include/node/config.gypi
gyp sill ignoring from tarball include/node/libplatform
gyp verb extracted file from tarball include/node/node.h
gyp verb extracted file from tarball include/node/node_api.h
gyp verb extracted file from tarball include/node/node_api_types.h
gyp verb extracted file from tarball include/node/node_buffer.h
gyp verb extracted file from tarball include/node/node_object_wrap.h
gyp verb extracted file from tarball include/node/node_version.h
gyp sill ignoring from tarball include/node/openssl
gyp verb extracted file from tarball include/node/pthread-barrier.h
gyp verb extracted file from tarball include/node/stdint-msvc2008.h
gyp verb extracted file from tarball include/node/tree.h
gyp verb extracted file from tarball include/node/uv-aix.h
gyp verb extracted file from tarball include/node/uv-bsd.h
gyp verb extracted file from tarball include/node/uv-darwin.h
gyp verb extracted file from tarball include/node/uv-errno.h
gyp verb extracted file from tarball include/node/uv-linux.h
gyp verb extracted file from tarball include/node/uv-os390.h
gyp verb extracted file from tarball include/node/uv-posix.h
gyp verb extracted file from tarball include/node/uv-sunos.h
gyp verb extracted file from tarball include/node/uv-threadpool.h
gyp verb extracted file from tarball include/node/uv-unix.h
gyp verb extracted file from tarball include/node/uv-version.h
gyp verb extracted file from tarball include/node/uv-win.h
gyp verb extracted file from tarball include/node/uv.h
gyp verb extracted file from tarball include/node/v8-debug.h
gyp verb extracted file from tarball include/node/v8-inspector-protocol.h
gyp verb extracted file from tarball include/node/v8-inspector.h
gyp verb extracted file from tarball include/node/v8-platform.h
gyp verb extracted file from tarball include/node/v8-profiler.h
gyp verb extracted file from tarball include/node/v8-testing.h
gyp verb extracted file from tarball include/node/v8-util.h
gyp verb extracted file from tarball include/node/v8-version-string.h
gyp verb extracted file from tarball include/node/v8-version.h
gyp verb extracted file from tarball include/node/v8.h
gyp verb extracted file from tarball include/node/v8config.h
gyp verb extracted file from tarball include/node/zconf.h
gyp verb extracted file from tarball include/node/zlib.h
gyp verb extracted file from tarball include/node/openssl/aes.h
gyp sill ignoring from tarball include/node/openssl/archs
gyp verb extracted file from tarball include/node/openssl/asn1.h
gyp verb extracted file from tarball include/node/openssl/asn1_mac.h
gyp verb extracted file from tarball include/node/openssl/asn1t.h
gyp verb extracted file from tarball include/node/openssl/bio.h
gyp verb extracted file from tarball include/node/openssl/blowfish.h
gyp verb extracted file from tarball include/node/openssl/bn.h
gyp verb extracted file from tarball include/node/openssl/buffer.h
gyp verb extracted file from tarball include/node/openssl/camellia.h
gyp verb extracted file from tarball include/node/openssl/cast.h
gyp verb extracted file from tarball include/node/openssl/cmac.h
gyp verb extracted file from tarball include/node/openssl/cms.h
gyp verb extracted file from tarball include/node/openssl/comp.h
gyp verb extracted file from tarball include/node/openssl/conf.h
gyp verb extracted file from tarball include/node/openssl/conf_api.h
gyp verb extracted file from tarball include/node/openssl/crypto.h
gyp verb extracted file from tarball include/node/openssl/des.h
gyp verb extracted file from tarball include/node/openssl/des_old.h
gyp verb extracted file from tarball include/node/openssl/dh.h
gyp verb extracted file from tarball include/node/openssl/dsa.h
gyp verb extracted file from tarball include/node/openssl/dso.h
gyp verb extracted file from tarball include/node/openssl/dtls1.h
gyp verb extracted file from tarball include/node/openssl/e_os2.h
gyp verb extracted file from tarball include/node/openssl/ebcdic.h
gyp verb extracted file from tarball include/node/openssl/ec.h
gyp verb extracted file from tarball include/node/openssl/ecdh.h
gyp verb extracted file from tarball include/node/openssl/ecdsa.h
gyp verb extracted file from tarball include/node/openssl/engine.h
gyp verb extracted file from tarball include/node/openssl/err.h
gyp verb extracted file from tarball include/node/openssl/evp.h
gyp verb extracted file from tarball include/node/openssl/hmac.h
gyp verb extracted file from tarball include/node/openssl/idea.h
gyp verb extracted file from tarball include/node/openssl/krb5_asn.h
gyp verb extracted file from tarball include/node/openssl/kssl.h
gyp verb extracted file from tarball include/node/openssl/lhash.h
gyp verb extracted file from tarball include/node/openssl/md4.h
gyp verb extracted file from tarball include/node/openssl/md5.h
gyp verb extracted file from tarball include/node/openssl/mdc2.h
gyp verb extracted file from tarball include/node/openssl/modes.h
gyp verb extracted file from tarball include/node/openssl/obj_mac.h
gyp verb extracted file from tarball include/node/openssl/objects.h
gyp verb extracted file from tarball include/node/openssl/ocsp.h
gyp verb extracted file from tarball include/node/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/opensslv.h
gyp verb extracted file from tarball include/node/openssl/ossl_typ.h
gyp verb extracted file from tarball include/node/openssl/pem.h
gyp verb extracted file from tarball include/node/openssl/pem2.h
gyp verb extracted file from tarball include/node/openssl/pkcs12.h
gyp verb extracted file from tarball include/node/openssl/pkcs7.h
gyp verb extracted file from tarball include/node/openssl/pqueue.h
gyp verb extracted file from tarball include/node/openssl/rand.h
gyp verb extracted file from tarball include/node/openssl/rc2.h
gyp verb extracted file from tarball include/node/openssl/rc4.h
gyp verb extracted file from tarball include/node/openssl/ripemd.h
gyp verb extracted file from tarball include/node/openssl/rsa.h
gyp verb extracted file from tarball include/node/openssl/safestack.h
gyp verb extracted file from tarball include/node/openssl/seed.h
gyp verb extracted file from tarball include/node/openssl/sha.h
gyp verb extracted file from tarball include/node/openssl/srp.h
gyp verb content checksum node-v8.2.1-headers.tar.gz 84976f3698f3a9764d434fc57df35bf4a312d4e52203ba13685817a9f1aa6805
gyp verb extracted file from tarball include/node/openssl/srtp.h
gyp verb extracted file from tarball include/node/openssl/ssl.h
gyp verb extracted file from tarball include/node/openssl/ssl2.h
gyp verb extracted file from tarball include/node/openssl/ssl23.h
gyp verb extracted file from tarball include/node/openssl/ssl3.h
gyp verb extracted file from tarball include/node/openssl/stack.h
gyp verb extracted file from tarball include/node/openssl/symhacks.h
gyp verb extracted file from tarball include/node/openssl/tls1.h
gyp verb extracted file from tarball include/node/openssl/ts.h
gyp verb extracted file from tarball include/node/openssl/txt_db.h
gyp verb extracted file from tarball include/node/openssl/ui.h
gyp verb extracted file from tarball include/node/openssl/ui_compat.h
gyp verb extracted file from tarball include/node/openssl/whrlpool.h
gyp verb extracted file from tarball include/node/openssl/x509.h
gyp verb extracted file from tarball include/node/openssl/x509_vfy.h
gyp verb extracted file from tarball include/node/openssl/x509v3.h
gyp sill ignoring from tarball include/node/openssl/archs/aix-gcc
gyp sill ignoring from tarball include/node/openssl/archs/aix64-gcc
gyp sill ignoring from tarball include/node/openssl/archs/BSD-x86
gyp sill ignoring from tarball include/node/openssl/archs/BSD-x86_64
gyp sill ignoring from tarball include/node/openssl/archs/darwin-i386-cc
gyp sill ignoring from tarball include/node/openssl/archs/darwin64-x86_64-cc
gyp sill ignoring from tarball include/node/openssl/archs/linux-aarch64
gyp sill ignoring from tarball include/node/openssl/archs/linux-armv4
gyp sill ignoring from tarball include/node/openssl/archs/linux-elf
gyp sill ignoring from tarball include/node/openssl/archs/linux-ppc
gyp sill ignoring from tarball include/node/openssl/archs/linux-ppc64
gyp sill ignoring from tarball include/node/openssl/archs/linux-x32
gyp sill ignoring from tarball include/node/openssl/archs/linux-x86_64
gyp sill ignoring from tarball include/node/openssl/archs/linux32-s390x
gyp sill ignoring from tarball include/node/openssl/archs/linux64-s390x
gyp sill ignoring from tarball include/node/openssl/archs/solaris-x86-gcc
gyp sill ignoring from tarball include/node/openssl/archs/solaris64-x86_64-gcc
gyp sill ignoring from tarball include/node/openssl/archs/VC-WIN32
gyp sill ignoring from tarball include/node/openssl/archs/VC-WIN64A
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN64A/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN32/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux32-s390x/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-x86_64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-x32/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-ppc64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-ppc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-elf/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-armv4/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-aarch64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/darwin-i386-cc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/BSD-x86_64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/BSD-x86/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/aix64-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/aix-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/libplatform/libplatform-export.h
gyp verb extracted file from tarball include/node/libplatform/libplatform.h
gyp verb extracted file from tarball include/node/libplatform/v8-tracing.h
gyp verb tarball done parsing tarball
gyp verb check download content checksum, need to download `SHASUMS256.txt`... 
gyp verb checksum url https://nodejs.org/download/release/v8.2.1/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v8.2.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.2.1/SHASUMS256.txt
gyp verb checksum data {"node-v8.2.1-aix-ppc64.tar.gz":"b6343e1d396dff5b29a62eff0550a7782a6b82b18625fb29cebd6735b30851f3","node-v8.2.1-darwin-x64.tar.gz":"32d0923c147470d57f18f055014f5a9fe8a3919406010a2e80ba85952d3c9923","node-v8.2.1-darwin-x64.tar.xz":"9f8eb5e5ee0a4a17a08b186543e945a7e995696af7726dd8c7325235e750917d","node-v8.2.1-headers.tar.gz":"84976f3698f3a9764d434fc57df35bf4a312d4e52203ba13685817a9f1aa6805","node-v8.2.1-headers.tar.xz":"0d57509e932d65535d74034eaa389576faad8cade613b73daed2ac01c1d99308","node-v8.2.1-linux-arm64.tar.gz":"914a031d02cbf759238fa1c051bc21739abfa15572eae77c03cc34c37031b3ef","node-v8.2.1-linux-arm64.tar.xz":"9ed01737f37d410067beeb42066e51f6d0385677c7d0daeeaf2e32cb2aca854a","node-v8.2.1-linux-armv6l.tar.gz":"b98a17579636cf6cc46f0fe721fcf3b0b360f27c77678754e1eebe27a70625f1","node-v8.2.1-linux-armv6l.tar.xz":"167ccad4c6a848a7b17ead0b2d95770e984a2c8d69ddd42ea78813174daee716","node-v8.2.1-linux-armv7l.tar.gz":"97a2752cfe0ee1ae9225de4a3787a79f4b82c5679122019aff20835b09ecb62e","node-v8.2.1-linux-armv7l.tar.xz":"52a3abbf9450fbb91b39aaa268977a593daa8fc7dec0925d32ac7afd3a3596e2","node-v8.2.1-linux-ppc64le.tar.gz":"b01cb4d1f04c52d68faf90157bc234e907b4206c0a4057e8911bdda184fd1f50","node-v8.2.1-linux-ppc64le.tar.xz":"8f1f6896b9f49159e6a6a8fcf7b8d68245b3f007296dd2898f01dbc3b29e88f3","node-v8.2.1-linux-ppc64.tar.gz":"15cac8d58ab6dc53b3a4356bd11401211b1e09f2076c4d7699d58015c7c88a01","node-v8.2.1-linux-ppc64.tar.xz":"e47cd5d9b3cc0946287f8254cb8d35f4c42bda35604e4446fb498af8de1c3a6b","node-v8.2.1-linux-s390x.tar.gz":"d8f391e401ab2124e0c47f5c497d497e9b80819ee30fcd94033825e52a1e1f70","node-v8.2.1-linux-s390x.tar.xz":"7af75022ec9a37fd59890add4a8165a7b6d6f9300bc94abab32a97de3fd0e7a8","node-v8.2.1-linux-x64.tar.gz":"c082cf6e7011d4222d476c86421ae6a656d7d34d3d34133260e19a7718de88c9","node-v8.2.1-linux-x64.tar.xz":"abcddeb95cc4465953b1edb0922d20e9b0b3de83688fc8150b863117032a978a","node-v8.2.1-linux-x86.tar.gz":"79d1364e09434bdfe0e925b1e7c80691d92cdbc3ad7384ddeacc793eaa54721d","node-v8.2.1-linux-x86.tar.xz":"4c2b25ce95eba27adea4f72713286d60b25e73d816a128c35110afaace3f3e2d","node-v8.2.1.pkg":"98971a1d66b2af304a36c8760e2dbea59c8fd173319f2dcbb76b929287232982","node-v8.2.1-sunos-x64.tar.gz":"1afa29cbb224711d25f4cd6dcf4581ea9e692720c7eb45928dbcaebe54a01a81","node-v8.2.1-sunos-x64.tar.xz":"20872f6e8165b7364dcb961dd0f20ba70b8a2b0fcc875356e7c85180be8a9d65","node-v8.2.1-sunos-x86.tar.gz":"0bfde8259c1ce4358fd6893add5ac662b2f70c81396388e0e9f23ae6c201ae06","node-v8.2.1-sunos-x86.tar.xz":"5438318c248230d8175f7edaee2dfb3a7590f54589d391a1608f6d59f56f9967","node-v8.2.1.tar.gz":"66fe1379bc7daf9a16c6b5c45ab695bf1cdcfae9738d2989e940104d6b31973f","node-v8.2.1.tar.xz":"02c46d8914540eea73d0ad33bf9f371a28aa0dc8c5d740948491fef044ad8c8b","node-v8.2.1-win-x64.7z":"1d4709a568ce470f968bef7da4141e071a141474306da55ed00e129d68ef2b39","node-v8.2.1-win-x64.zip":"37e84e54c67e3d1e52d657c04835b211c94631a0b358f4e7dc351618fdb6c083","node-v8.2.1-win-x86.7z":"91494c1f4c514770113ccae9069077d567579d0ad7d65547ba32a5682d1d7ffb","node-v8.2.1-win-x86.zip":"b4f099c524a12cdf5d1a300c45b3397babf1121a3f56e071d6552c1df7566b0c","node-v8.2.1-x64.msi":"552aeb03a91a95a1b8e5737ba42feed670f59e284b463c17ad00eafa51e31076","node-v8.2.1-x86.msi":"38377ab5acd1dff77a36c980878f48e9a51fa00d4ae471631d2bb5b578cb18e1","win-x64/node.exe":"42a102369b8d2eac890f29e8316fd3119855cf32db53e817438ffcf1e233137b","win-x64/node.lib":"2eb4f69283027434ddb2a44f0573ff485a3d33ebd62cc96cfe492c62cebad891","win-x64/node_pdb.7z":"635dd154d25f5a7c29136c655b3b2952e4bf99135edc08e2d19dc4211fc992ca","win-x64/node_pdb.zip":"c5c07ddf6b799a0a9a11906257a1ab5c4da6ec8ba712fdaabb3d7332c8ebe100","win-x86/node.exe":"8683dff095f84f50589cf0e4855c7357c5190ea6d53aabf67e6f3f074d5cf18a","win-x86/node.lib":"63ab5292ff96f869c43efb3f5f584390fc713c454b19f31842ba418e8781f307","win-x86/node_pdb.7z":"c546a4fd1c9f69be98e19a83db6b0bf7749075fb396a03f2f518f91ee20270cb","win-x86/node_pdb.zip":"c5d78cbceecb503966be96778b771a96951f9cb8991175214e6c71ef731b096e"}
gyp verb download contents checksum {"node-v8.2.1-headers.tar.gz":"84976f3698f3a9764d434fc57df35bf4a312d4e52203ba13685817a9f1aa6805"}
gyp verb validating download checksum for node-v8.2.1-headers.tar.gz (84976f3698f3a9764d434fc57df35bf4a312d4e52203ba13685817a9f1aa6805 == 84976f3698f3a9764d434fc57df35bf4a312d4e52203ba13685817a9f1aa6805)
gyp verb get node dir target node version installed: 8.2.1
gyp verb build dir attempting to create "build" dir: /home/paul/node-kinect/build
gyp verb build dir "build" dir needed to be created? /home/paul/node-kinect/build
gyp verb build/config.gypi creating config file
gyp sill build/config.gypi { target_defaults: 
gyp sill build/config.gypi    { cflags: [],
gyp sill build/config.gypi      default_configuration: 'Release',
gyp sill build/config.gypi      defines: [],
gyp sill build/config.gypi      include_dirs: [],
gyp sill build/config.gypi      libraries: [] },
gyp sill build/config.gypi   variables: 
gyp sill build/config.gypi    { asan: 0,
gyp sill build/config.gypi      coverage: false,
gyp sill build/config.gypi      debug_devtools: 'node',
gyp sill build/config.gypi      force_dynamic_crt: 0,
gyp sill build/config.gypi      gas_version: '2.23',
gyp sill build/config.gypi      host_arch: 'x64',
gyp sill build/config.gypi      icu_data_file: 'icudt59l.dat',
gyp sill build/config.gypi      icu_data_in: '../../deps/icu-small/source/data/in/icudt59l.dat',
gyp sill build/config.gypi      icu_endianness: 'l',
gyp sill build/config.gypi      icu_gyp_path: 'tools/icu/icu-generic.gyp',
gyp sill build/config.gypi      icu_locales: 'en,root',
gyp sill build/config.gypi      icu_path: 'deps/icu-small',
gyp sill build/config.gypi      icu_small: true,
gyp sill build/config.gypi      icu_ver_major: '59',
gyp sill build/config.gypi      node_byteorder: 'little',
gyp sill build/config.gypi      node_enable_d8: false,
gyp sill build/config.gypi      node_enable_v8_vtunejit: false,
gyp sill build/config.gypi      node_install_npm: true,
gyp sill build/config.gypi      node_module_version: 57,
gyp sill build/config.gypi      node_no_browser_globals: false,
gyp sill build/config.gypi      node_prefix: '/',
gyp sill build/config.gypi      node_release_urlbase: 'https://nodejs.org/download/release/',
gyp sill build/config.gypi      node_shared: false,
gyp sill build/config.gypi      node_shared_cares: false,
gyp sill build/config.gypi      node_shared_http_parser: false,
gyp sill build/config.gypi      node_shared_libuv: false,
gyp sill build/config.gypi      node_shared_openssl: false,
gyp sill build/config.gypi      node_shared_zlib: false,
gyp sill build/config.gypi      node_tag: '',
gyp sill build/config.gypi      node_use_bundled_v8: true,
gyp sill build/config.gypi      node_use_dtrace: false,
gyp sill build/config.gypi      node_use_etw: false,
gyp sill build/config.gypi      node_use_lttng: false,
gyp sill build/config.gypi      node_use_openssl: true,
gyp sill build/config.gypi      node_use_perfctr: false,
gyp sill build/config.gypi      node_use_v8_platform: true,
gyp sill build/config.gypi      node_without_node_options: false,
gyp sill build/config.gypi      openssl_fips: '',
gyp sill build/config.gypi      openssl_no_asm: 0,
gyp sill build/config.gypi      shlib_suffix: 'so.57',
gyp sill build/config.gypi      target_arch: 'x64',
gyp sill build/config.gypi      uv_parent_path: '/deps/uv/',
gyp sill build/config.gypi      uv_use_dtrace: false,
gyp sill build/config.gypi      v8_enable_gdbjit: 0,
gyp sill build/config.gypi      v8_enable_i18n_support: 1,
gyp sill build/config.gypi      v8_enable_inspector: 1,
gyp sill build/config.gypi      v8_no_strict_aliasing: 1,
gyp sill build/config.gypi      v8_optimized_debug: 0,
gyp sill build/config.gypi      v8_promise_internal_field_count: 1,
gyp sill build/config.gypi      v8_random_seed: 0,
gyp sill build/config.gypi      v8_trace_maps: 0,
gyp sill build/config.gypi      v8_use_snapshot: false,
gyp sill build/config.gypi      want_separate_host_toolset: 0,
gyp sill build/config.gypi      want_separate_host_toolset_mkpeephole: 0,
gyp sill build/config.gypi      nodedir: '/home/paul/.node-gyp/8.2.1',
gyp sill build/config.gypi      standalone_static_library: 1,
gyp sill build/config.gypi      cache_lock_stale: '60000',
gyp sill build/config.gypi      ham_it_up: '',
gyp sill build/config.gypi      legacy_bundling: '',
gyp sill build/config.gypi      sign_git_tag: '',
gyp sill build/config.gypi      user_agent: 'npm/5.3.0 node/v8.2.1 linux x64',
gyp sill build/config.gypi      always_auth: '',
gyp sill build/config.gypi      bin_links: 'true',
gyp sill build/config.gypi      key: '',
gyp sill build/config.gypi      allow_same_version: '',
gyp sill build/config.gypi      description: 'true',
gyp sill build/config.gypi      fetch_retries: '2',
gyp sill build/config.gypi      heading: 'npm',
gyp sill build/config.gypi      if_present: '',
gyp sill build/config.gypi      init_version: '1.0.0',
gyp sill build/config.gypi      user: '',
gyp sill build/config.gypi      prefer_online: '',
gyp sill build/config.gypi      force: '',
gyp sill build/config.gypi      only: '',
gyp sill build/config.gypi      cache_min: '10',
gyp sill build/config.gypi      init_license: 'ISC',
gyp sill build/config.gypi      editor: 'vi',
gyp sill build/config.gypi      rollback: 'true',
gyp sill build/config.gypi      tag_version_prefix: 'v',
gyp sill build/config.gypi      cache_max: 'Infinity',
gyp sill build/config.gypi      timing: '',
gyp sill build/config.gypi      userconfig: '/home/paul/.npmrc',
gyp sill build/config.gypi      engine_strict: '',
gyp sill build/config.gypi      init_author_name: '',
gyp sill build/config.gypi      init_author_url: '',
gyp sill build/config.gypi      tmp: '/tmp',
gyp sill build/config.gypi      depth: 'Infinity',
gyp sill build/config.gypi      save_dev: '',
gyp sill build/config.gypi      usage: '',
gyp sill build/config.gypi      metrics_registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      package_lock: 'true',
gyp sill build/config.gypi      progress: 'true',
gyp sill build/config.gypi      https_proxy: '',
gyp sill build/config.gypi      save_prod: '',
gyp sill build/config.gypi      onload_script: '',
gyp sill build/config.gypi      sso_type: 'oauth',
gyp sill build/config.gypi      rebuild_bundle: 'true',
gyp sill build/config.gypi      save_bundle: '',
gyp sill build/config.gypi      shell: '/bin/bash',
gyp sill build/config.gypi      dry_run: '',
gyp sill build/config.gypi      prefix: '/usr/local',
gyp sill build/config.gypi      scope: '',
gyp sill build/config.gypi      browser: '',
gyp sill build/config.gypi      cache_lock_wait: '10000',
gyp sill build/config.gypi      ignore_prepublish: '',
gyp sill build/config.gypi      registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      save_optional: '',
gyp sill build/config.gypi      searchopts: '',
gyp sill build/config.gypi      versions: '',
gyp sill build/config.gypi      cache: '/home/paul/.npm',
gyp sill build/config.gypi      send_metrics: '',
gyp sill build/config.gypi      global_style: '',
gyp sill build/config.gypi      ignore_scripts: '',
gyp sill build/config.gypi      version: '',
gyp sill build/config.gypi      local_address: '',
gyp sill build/config.gypi      viewer: 'man',
gyp sill build/config.gypi      prefer_offline: '',
gyp sill build/config.gypi      color: 'true',
gyp sill build/config.gypi      fetch_retry_mintimeout: '10000',
gyp sill build/config.gypi      maxsockets: '50',
gyp sill build/config.gypi      offline: '',
gyp sill build/config.gypi      sso_poll_frequency: '500',
gyp sill build/config.gypi      umask: '0022',
gyp sill build/config.gypi      fetch_retry_maxtimeout: '60000',
gyp sill build/config.gypi      logs_max: '10',
gyp sill build/config.gypi      message: '%s',
gyp sill build/config.gypi      ca: '',
gyp sill build/config.gypi      cert: '',
gyp sill build/config.gypi      global: '',
gyp sill build/config.gypi      link: '',
gyp sill build/config.gypi      access: '',
gyp sill build/config.gypi      also: '',
gyp sill build/config.gypi      save: 'true',
gyp sill build/config.gypi      unicode: 'true',
gyp sill build/config.gypi      long: '',
gyp sill build/config.gypi      production: '',
gyp sill build/config.gypi      searchlimit: '20',
gyp sill build/config.gypi      unsafe_perm: 'true',
gyp sill build/config.gypi      auth_type: 'legacy',
gyp sill build/config.gypi      node_version: '8.2.1',
gyp sill build/config.gypi      tag: 'latest',
gyp sill build/config.gypi      git_tag_version: 'true',
gyp sill build/config.gypi      script_shell: '',
gyp sill build/config.gypi      shrinkwrap: 'true',
gyp sill build/config.gypi      fetch_retry_factor: '10',
gyp sill build/config.gypi      proprietary_attribs: 'true',
gyp sill build/config.gypi      save_exact: '',
gyp sill build/config.gypi      strict_ssl: 'true',
gyp sill build/config.gypi      dev: '',
gyp sill build/config.gypi      globalconfig: '/usr/local/etc/npmrc',
gyp sill build/config.gypi      init_module: '/home/paul/.npm-init.js',
gyp sill build/config.gypi      parseable: '',
gyp sill build/config.gypi      globalignorefile: '/usr/local/etc/npmignore',
gyp sill build/config.gypi      cache_lock_retries: '10',
gyp sill build/config.gypi      searchstaleness: '900',
gyp sill build/config.gypi      save_prefix: '^',
gyp sill build/config.gypi      scripts_prepend_node_path: 'warn-only',
gyp sill build/config.gypi      group: '1000',
gyp sill build/config.gypi      init_author_email: '',
gyp sill build/config.gypi      searchexclude: '',
gyp sill build/config.gypi      git: 'git',
gyp sill build/config.gypi      optional: 'true',
gyp sill build/config.gypi      json: '' } }
gyp verb build/config.gypi writing out config file: /home/paul/node-kinect/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/paul/node-kinect/config.gypi
gyp verb common.gypi checking for gypi file: /home/paul/node-kinect/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/paul/node-kinect/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/paul/.node-gyp/8.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/paul/.node-gyp/8.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/paul/.node-gyp/8.2.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/paul/node-kinect',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/paul/.node-gyp/8.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/paul/node-kinect/build'
  CXX(target) Release/obj.target/kinect/src/kinect.o
../src/kinect.cc:11:39: fatal error: libfreenect/libfreenect.h: No such file or directory
   #include <libfreenect/libfreenect.h>
                                       ^
compilation terminated.
make: *** [Release/obj.target/kinect/src/kinect.o] Error 1
make: Leaving directory `/home/paul/node-kinect/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/paul/node-kinect
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kinect@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kinect@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2017-08-12T13_39_09_853Z-debug.log
</pre>

**Comment by eriknoorland** [comment]
@corpr8 Did you manage to solve this? I'm running into the same issue on my Raspberry Pi.

**Comment by talk2dug** [comment]
bump
