### ISSUE TITLE
running 'npm test' error

### ISSUE THREAD

**Issue by kod3000** [nguyer/node-kinect#3]
## I do the following steps

``` sh
cd Desktop
git clone git://github.com/pgte/node-kinect.git
cd node-kinect
node-gyp configure
node-gyp build
npm test
```
## when I run this command

``` sh
npm test
```
## I get the following error..

``` sh
magnus:node-kinect Username$ npm test

> kinect@0.1.7 test /Users/Username/Desktop/test/node-kinect
> node_modules/.bin/mocha test/*.js


module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Symbol kinect_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Username/Desktop/test/node-kinect/kinect.js:1:82)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Username/Desktop/test/node-kinect/test/base.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/Username/Desktop/test/node-kinect/node_modules/mocha/lib/mocha.js:152:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/Username/Desktop/test/node-kinect/node_modules/mocha/lib/mocha.js:149:14)
    at Mocha.run (/Users/Username/Desktop/test/node-kinect/node_modules/mocha/lib/mocha.js:305:31)
    at Object.<anonymous> (/Users/Username/Desktop/test/node-kinect/node_modules/mocha/bin/_mocha:327:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

```

I'm using :
_osX 10.8.3_
_node 0.10.2_

any ideas on this? :question: :confused:

**Comment by psayre23** [comment]
I'm getting the same error. OSX 10.7.5, Node 0.10.4, libusb 1.0.9, libfreenect 0.1.2
